name: Neo Run Tests
description: Запускает установку зависимостей, тесты и проверку PEP8

runs:
  using: "composite"
  steps:
    - run: python -m pip install --upgrade pip
      shell: bash

    - run: pip install -r requirements.txt
      shell: bash

    - run: python -m unittest discover
      shell: bash

    - run: |
        echo "Проверка кода на PEP8"
        flake8 app.py
      shell: bash
