name: 'My CICD Template'
description: 'Установка, тесты, сборка, проверка и деплой'

runs:
  using: "composite"
  steps:
    - name: Установка зависимостей
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python -m unittest discover

    - name: Проверка кода на PEP8
      run: |
        echo "Проверка кода на PEP8"
        flake8 app.py

    - name: Set image tag from commit SHA
      id: vars
      run: echo "TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: anvarjn/anvar3235.dev:${{ env.TAG }}

    - name: Run app in background
      run: |
        docker build -t anvarjn/anvar3235.dev:${{ env.TAG }} .
        docker run -d -p 5000:5000 anvarjn/anvar3235.dev:${{ env.TAG }}
        sleep 3

    - name: Проверка /health endpoint
      run: |
        curl --fail http://127.0.0.1:5000/health

    - name: Проверка /version endpoint
      run: |
        curl --fail http://127.0.0.1:5000/version
